package com.finger.usbcamera.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.finger.usbcamera.db.entity.Face;
import com.finger.usbcamera.db.entity.Finger;
import com.finger.usbcamera.db.entity.Person;
import com.finger.usbcamera.db.entity.User;

import com.finger.usbcamera.db.greendao.FaceDao;
import com.finger.usbcamera.db.greendao.FingerDao;
import com.finger.usbcamera.db.greendao.PersonDao;
import com.finger.usbcamera.db.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceDaoConfig;
    private final DaoConfig fingerDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FaceDao faceDao;
    private final FingerDao fingerDao;
    private final PersonDao personDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceDaoConfig = daoConfigMap.get(FaceDao.class).clone();
        faceDaoConfig.initIdentityScope(type);

        fingerDaoConfig = daoConfigMap.get(FingerDao.class).clone();
        fingerDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        faceDao = new FaceDao(faceDaoConfig, this);
        fingerDao = new FingerDao(fingerDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Face.class, faceDao);
        registerDao(Finger.class, fingerDao);
        registerDao(Person.class, personDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        faceDaoConfig.clearIdentityScope();
        fingerDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FaceDao getFaceDao() {
        return faceDao;
    }

    public FingerDao getFingerDao() {
        return fingerDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
