package com.finger.usbcamera.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.finger.usbcamera.db.entity.Finger;
import com.finger.usbcamera.db.entity.Person;

import com.finger.usbcamera.db.greendao.FingerDao;
import com.finger.usbcamera.db.greendao.PersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fingerDaoConfig;
    private final DaoConfig personDaoConfig;

    private final FingerDao fingerDao;
    private final PersonDao personDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fingerDaoConfig = daoConfigMap.get(FingerDao.class).clone();
        fingerDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        fingerDao = new FingerDao(fingerDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);

        registerDao(Finger.class, fingerDao);
        registerDao(Person.class, personDao);
    }
    
    public void clear() {
        fingerDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
    }

    public FingerDao getFingerDao() {
        return fingerDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

}
